# Generated by Django 3.1.1 on 2020-09-18 10:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0002_sportnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 9, 18, 10, 19, 27, 912237, tzinfo=utc)),
        ),
    ]
